// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifacrqzfysfnnfpnyabo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmYWNycXpmeXNmbm5mcG55YWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjgzMDIsImV4cCI6MjA3MTYwNDMwMn0.Uwi0nxkp0lDyiSgGZUH7AdbN_Z8bKmm9-S8AwIDIsBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});